### PR TITLE
Add indentation + whitespace

### PR DESCRIPTION
**Pull request by christopher-dG**
If you prefer things the way they are that's fine, but I would argue that it's completely unreadable as-is.

### CODE REVIEW

**Comment by christopher-dG** [comment]
Updated to include the new code, feel free to merge if you like

e: also made the scripts executable by default

**Comment by hakerdefo** [comment]
Thank you @christopher-dG for making pmss and pmss-legacy easier to read. Really appreciated. I have merged all the changes to pmss and pmss-legacy. I'm keeping the,

> Next make it executable,
`sudo chmod 755 /usr/local/bin/pmss`

part in the README for the benefits of the web interface users.

Cheers!!!

**Comment by christopher-dG** [comment]
For future reference/the benefit of future contributors, you can just use the merge functionality to apply the changes (and credit those who submitted them). 🙂 

Also my last commit applied the `chmod` step automatically, so it really wasn't necessary to keep that line in the readme (it was redundant, or at least it was on my branch).

**Comment by hakerdefo** [comment]
Hi @christopher-dG,
If someone downloads the repository via a browser then the execute permissions are not retained. This is the reason to keep the line in the README.
Cheers!!!

**Comment by christopher-dG** [comment]
No one does that though, `git clone` exists for a reason 😉

**Pull request closed without merging**
